name: verisync
description: "Verisync simplifies KYC for clients and customers. It's easy to integrate into Flutter projects and supports IOS, Android, Windows, and Web."

version: 0.0.7
homepage: https://verisync.co/policies
repository: https://github.com/verisync/verisync-flutter

environment:
  sdk: '>=3.2.6 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_inappwebview: ^6.0.0
  permission_handler: ^11.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  
flutter:

  
  
  
  
  
  
  
  
  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
